Repository dmu-most/vblog-client, pull requests merged in 2023-10, with the labels that each got.

#44 feat: 마이페이지 회원정보 수정 레이아웃 구현
  README.md
  src/api/axiosInstance.ts
  src/api/myInfo.ts
  src/components/my-info/MyInfoContent.tsx
  src/components/my-info/ProfileDescription.tsx
  src/components/my-info/ProfileImageEdit.tsx
  src/components/my-info/ProfileNameEdit.tsx
  src/components/my-info/SocialIcons.tsx
  src/components/my-info/UserProfileUpdate.tsx
  src/pages/MyPage.tsx
  src/types/myInfo.ts
Labels: 🐞 BugFix, 🔥 Feature

#46 feat: 마이페이지 회원정보 수정 기능 구현
  src/api/axiosInstance.ts
  src/api/myInfo.ts
  src/components/header/RightHeader.tsx
  src/components/my-info/ProfileDescription.tsx
  src/components/my-info/ProfileImageEdit.tsx
  src/components/my-info/UserProfileUpdate.tsx
  src/types/myInfo.ts
Labels: 🔥 Feature

#47 rename: 폴더 생성 및 파일 세분화
  src/api/auth/index.ts
  src/api/my-info/content.ts
  src/api/my-info/index.ts
  src/api/my-info/member.ts
  src/components/my-info/ProfileDescription.tsx
  src/components/my-info/ProfileImageEdit.tsx
  src/components/my-info/UserProfileUpdate.tsx
  src/types/auth/index.ts
  src/types/index.ts
  src/types/my-info/content.ts
  src/types/my-info/index.ts
  src/types/my-info/member.ts
  src/types/myInfo.ts
Labels: 🛠 Refector

#48 브이로그/블로그 최근 기록 및 리뷰 레이아웃 구현
  src/api/my-info/content.ts
  src/components/my-info/MyInfoContent.tsx
  src/components/my-info/MyRecentItem.tsx
  src/components/my-info/MyRecentList.tsx
  src/components/my-info/MyReviewItem.tsx
  src/components/my-info/MyReviewList.tsx
  src/components/my-info/ReviewPagination.tsx
  src/types/my-info/content.ts
Labels: 🎨 HTML&CSS

#49 api: 리뷰 작성 , 사용자 알고리즘 api 서버 연결(수정 필요)
  package-lock.json
  package.json
  src/api/detail/review.ts
  src/api/main/vblogList.ts
  src/components/detail/ReviewComponent.tsx
  src/components/detail/modal/RatingModal.tsx
  src/components/main/CardComponent.tsx
  src/components/main/UserCardComponent.tsx
  src/pages/MainPage.tsx
  src/types/detail/review.ts
Labels: 📬 API, 🔥 Feature

#51 Review04 jh
  src/api/detail/review.ts
  src/components/common/ReviewForm.tsx
  src/components/detail/ReviewComponent.tsx
  src/components/detail/modal/RatingModal.tsx
  src/types/detail/review.ts
Labels: 📬 API, 🔥 Feature

#52 feat: 마이페이지 카테고리 레이아웃 구현 및 버그 수정
  src/api/detail/content.ts
  src/api/detail/index.ts
  src/api/my-info/content.ts
  src/components/my-info/InterestList.tsx
  src/components/my-info/MyInfoContent.tsx
  src/components/my-info/MyRecentItem.tsx
  src/components/my-info/MyRecentList.tsx
  src/components/my-info/MyReviewItem.tsx
  src/components/my-info/MyReviewList.tsx
  src/components/my-info/MyScrapList.tsx
  src/components/my-info/ReviewPagination.tsx
  src/components/my-info/UserProfileUpdate.tsx
  src/components/sign/LoginForm.tsx
  src/pages/DetailPage.tsx
  src/types/detail/index.ts
  src/types/detail/vblog.ts
  src/types/index.ts
  src/types/my-info/content.ts
Labels: 🐞 BugFix, 🔥 Feature, 🎨 HTML&CSS

#53 feat: 좋아요,싫어요,스크랩 UI 수정 , 스크랩 모달 UI 구성
  src/api/detail/index.ts
  src/api/detail/vblogContent.ts
  src/api/detail/vblogInfo.ts
  src/api/main/index.ts
  src/api/main/vblogList.ts
  src/components/common/BannerTag.tsx
  src/components/common/ReviewForm.tsx
  src/components/detail/CommandComponent.tsx
  src/components/detail/ContentComonent.tsx
  src/components/detail/LikeDisLikeButton.tsx
  src/components/detail/ReviewComponent.tsx
  src/components/detail/modal/ScrapModal.tsx
  src/components/main/CardComponent.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/types/detail/vblog.ts
Labels: 🔥 Feature, 🎨 HTML&CSS

#54 feat: 타입쪽 머지 충돌 추가 수정
  src/types/detail/vblog.ts
Labels: 🐞 BugFix

#55 마이페이지 리뷰 조회, 수정, 삭제 및 최근 기록 조회 기능 구현
  public/assets/images/undefined.png
  public/assets/images/undefined2.png
  src/api/my-info/content.ts
  src/components/common/ReviewForm.tsx
  src/components/common/UndefinedData.tsx
  src/components/detail/ReviewComponent.tsx
  src/components/my-info/EditReview.tsx
  src/components/my-info/MyInfoContent.tsx
  src/components/my-info/MyRecentItem.tsx
  src/components/my-info/MyRecentList.tsx
  src/components/my-info/MyReviewItem.tsx
  src/components/my-info/MyReviewList.tsx
  src/components/my-info/MyScrapList.tsx
  src/components/my-info/ReviewPagination.tsx
  src/components/my-info/UserProfileUpdate.tsx
  src/types/my-info/content.ts
Labels: 📬 API, 🔥 Feature

#56 style: 마이페이지 ul 여백 수정
  src/components/my-info/MyInfoContent.tsx
  src/components/my-info/MyReviewList.tsx
Labels: 🎨 HTML&CSS

#58 api: 개인 알고리즘, 좋아요/싫어요 서버 연결
  src/api/detail/vblogInfo.ts
  src/api/main/vblogList.ts
  src/components/detail/ContentComonent.tsx
  src/components/detail/LikeDisLikeButton.tsx
  src/components/main/UserCardComponent.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/store/useLikeDislikeStore.ts
Labels: 📬 API, 🔥 Feature
