Repository dmu-most/vblog-client, pull requests merged in 2023-09, with the labels that each got.

#28 Feat/signup/#11
  src/Router.tsx
  src/api/auth/login.ts
  src/api/auth/signUp.ts
  src/api/axiosInstance.ts
  src/components/sign/LoginForm.tsx
  src/components/sign/LoginHeader.tsx
  src/components/sign/SignUpForm.tsx
  src/pages/LoginPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/store/useTokenStore.ts
  src/types/auth/login.ts
  src/types/auth/signUp.ts
  src/utils/formValidation.ts
Labels: 📬 API, 🐞 BugFix, 🔥 Feature

#31 feat: 헤더 드롭다운 기능 구현
  src/components/header/MyInfoDropDowm.tsx
  src/components/header/RightHeader.tsx
  src/components/header/UserLoginBtn.tsx
  src/components/sign/LoginForm.tsx
  src/store/useMemberStore.ts
  src/store/useTokenStore.ts
  src/types/auth/login.ts
Labels: 🐞 BugFix, 🔥 Feature

#32 api: 회원정보 조회 API 연결 및 axios instance 수정
  src/api/auth/login.ts
  src/api/auth/signUp.ts
  src/api/auth/token.ts
  src/api/axiosInstance.ts
  src/api/myInfo.ts
  src/components/header/MyInfoDropDowm.tsx
  src/components/header/RightHeader.tsx
  src/components/my-info/ProfileDescription.tsx
  src/types/auth/token.ts
  src/types/myInfo.ts
Labels: 📬 API, 🐞 BugFix, 🔥 Feature

#36 api: categoryPage API 연결 및 noimage 생성
  public/assets/images/noimage.png
  src/Router.tsx
  src/components/Category/CategotyCardComponent.tsx
  src/components/common/PostCard.tsx
  src/components/detail/ContentComonent.tsx
Labels: 📬 API, 🔥 Feature

#38 feat: 콘텐츠 최대 너비 및 모바일 쿼리 추가
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/Main.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
Labels: 🔥 Feature, 🎨 HTML&CSS

#39 feat: OAuth 소셜 로그인 기능 추가
  src/components/header/MyInfoDropDown.tsx
  src/components/header/RightHeader.tsx
  src/components/my-info/ProfileDescription.tsx
  src/components/sign/LoginHeader.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/Main.tsx
  src/pages/OauthCallbackPage.tsx
  src/pages/SignUpPage.tsx
  src/types/auth/login.ts
Labels: 🐞 BugFix, 🔥 Feature

#40 feat: mainpage layout 수정
  src/components/common/PostCard.tsx
  src/components/main/BannerComponent.tsx
  src/components/main/CardComponent.tsx
  src/components/main/IntroComponent.tsx
  src/pages/MainPage.tsx
Labels: 🎨 HTML&CSS

#41 style: 카드 컴포넌트 및 메인 CSS 다듬기
  public/favicon.ico
  src/components/common/PostCard.tsx
  src/components/main/BannerComponent.tsx
  src/components/main/CardComponent.tsx
  src/components/main/IntroComponent.tsx
  src/pages/MainPage.tsx
  src/utils/truncatedText.ts
Labels: 🎨 HTML&CSS

#42 feat: react-spinner 설치 fix: categoryPage 무한스크롤 버그 수정
  package-lock.json
  package.json
  src/components/Category/CategoryDropdown.tsx
  src/components/Category/CategotyCardComponent.tsx
  src/styles/GlobalStyles.ts
Labels: 🐞 BugFix, 🔥 Feature

#43 api: 카테고리 최신순/인기순 api 서버 연결 , feat: 찜 UI , review dummydata 추가
  package-lock.json
  package.json
  src/components/Category/CategoryDropdown.tsx
  src/components/Category/CategotyCardComponent.tsx
  src/components/common/Hashtag.tsx
  src/components/common/PostCard.tsx
  src/components/common/ReviewForm.tsx
  src/components/detail/CommandComponent.tsx
  src/components/detail/ContentComonent.tsx
  src/components/detail/ReviewComponent.tsx
  src/data/dummyData.ts
  src/pages/CategoryPage.tsx
  src/types/detail/review.ts
  src/types/detail/vblog.ts
  src/types/main/list.ts
Labels: 📬 API, 🔥 Feature, 🎨 HTML&CSS
